logging:
    file:
        name: ${java.io.tmpdir}/application.log
    level:
        com:
            backend: DEBUG
        org:
            springframework: DEBUG
            springframework.web: DEBUG
app:
    admin:
        confirm-url: /admin/auth/password?token=
        reset-url: /admin/auth/new?token=
        url: http://185.185.126.15
    email:
        reset:
            content: 'Go to the link provided to reset your password: %s'
            subject: Password reset subject
        sending-enabled: true
jwt:
    expiration: 3600
    secret: test112322
server:
    port: 8080
    servlet:
        context-path: /engine
security:
    jwt:
        token:
            secret-key: secret-key
            expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds
spring:
    profiles:
        active: local 
    data:
        rest:
            basePath: /engine
    jackson:
        default-property-inclusion: non_null
    jmx:
        enabled: false
    mail:
        default-encoding: UTF-8
        host: smtp-relay.sendinblue.com
        password: 5jzOYV6KpQLgGJrq
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    connectiontimeout: 5000
                    starttls:
                        enable: true
                    timeout: 5000
                    writetimeout: 5000
        protocol: smtp
        test-connection: true
        username: peter.penzov@gmail.com
    production:
        datasource:
            driver-class-name: org.mariadb.jdbc.Driver
            jdbc-url: jdbc:mariadb://localhost:3306/engine_production
            jpa:
                hibernate:
                    ddl-auto: update
                properties:
                    hibernate:
                        dialect: org.hibernate.dialect.MariaDBDialect
                show-sql: true
            password: qwerty
            username: root    
    warehouse:
        datasource:
            driver-class-name: org.mariadb.jdbc.Driver
            jdbc-url: jdbc:mariadb://localhost:3306/engine_warehouse
            jpa:
                hibernate:
                    ddl-auto: update
                properties:
                    hibernate:
                        dialect: org.hibernate.dialect.MariaDBDialect
                show-sql: true
            password: qwerty
            username: root
